### ISSUE TITLE
tunerのopenが遅い

### ISSUE THREAD

**Issue by miutaku** [tsukumijima/px4_drv#10]
# 概要

PX-Q3PE4を利用しているのですが、チューナーのopenに(？)時間がかかります。
およそ10秒弱程度でしょうか。時間がかかります。
インストール方法としては、`sudo apt install ./px4-drv-dkms_0.4.5_all.deb`しています。

# 検証方法

Miraktestを利用して該当チューナーサーバに接続し、再生開始までの時間を測定すると、おおよそ10秒程度かかっております。
また、EPGStationにて録画する際も、録画された番組の冒頭10秒程度が欠けてしまう状態です。

**Comment by tsukumijima** [comment]
少なくとも手元環境の PX-W3U4 ではそこまで時間かからないですし、10秒近くかかるというのは聞いたことがないです。
おそらくですがチューナーの不調、そうでなくても環境依存の問題と思われます。
とはいえ冒頭が欠ける問題に関しては Mirakurun 側の設定を変更することで対処可能なはずです。とはいえ明示的に録画マージンを指定できる訳ではないので、私としては録画マージンが指定可能で EPGStation よりも追従に強い https://github.com/tsukumijima/EDCB-Wine の利用をお勧めしています。

**Comment by miutaku** [comment]
迅速なご返答ありがとうございます。
`maxBufferBytesBeforeReady`にて一旦暫定的に対処し、様子見してみます。
また、EDCB-Wineの方も検証環境にて利用してみようと思います。

本件、各SNS等を確認してもおま環の可能性が高そうなので、closeさせていただきます。
もしも本issueをopenしたほうが良さそうであればその際はまたopenさせていただくかもしれません。
