### ISSUE TITLE
Dynamic Major / Minor Number Make LXC Difficult

### ISSUE THREAD

**Issue by aftertommy** [tsukumijima/px4_drv#17]
英語で失礼します。

## Background 

I'm setting up a proxmox server with a plex card. I need to pass this device through to an LXC that will run `recpt1`. `px4_drv` is working fine.

However, in order to pass through the device, I need to specify the following in the `LXC.conf` file:

```
// etc/pve/lxc/100.conf

// pass through devices matching major number 236
lxc.cgroup2.devices.allow: c 236:* rwm
```

`236` is the major number of the `px4video` devices:

```bash
# ls -al /dev/px4video*
crw-rw-rw- 1 root video 236, 0 Dec 31 00:42 /dev/px4video0
crw-rw-rw- 1 root video 236, 1 Dec 31 00:42 /dev/px4video1
crw-rw-rw- 1 root video 236, 2 Dec 31 00:42 /dev/px4video2
crw-rw-rw- 1 root video 236, 3 Dec 31 00:42 /dev/px4video3
```

## The Problem

When I restart the server, sometimes the major number of the device changes. This leads to the passthrough to the LXC breaking, and `recpt1` running inside the LXC will no longer work.

I believe this is because `px4_drv` is using `alloc_chrdev_region` to allocate the major / minor number pair, which allows the kernel to return different numbers each call.

I think if `px4_drv` switched to using `register_chrdev_region`, and registered a static major number, that would resolve the issues I'm seeing.

Perhaps this could be a compile-time option, and I can pass in my own major number? 

Please see this [Japanese blog](https://blog.yakijake.net/lxc-dtv-px4_drv-1/) that mentions the same problem, but they don't seem to understand why it's happening.

**Comment by aftertommy** [comment]
Thinking about it more, I could probably instead write a udev rule that modified the LXC .conf file to add those lines when the device is attached...

**Comment by aftertommy** [comment]
I'm going to close this since there are several workarounds available and I'm not sure it's correct for the driver to have to make a change for normal usage. Updating my conf with this:

```
lxc.cgroup2.devices.allow: c *:* rwm
```

**Comment by masato-yoshi-dnsalias-com** [comment]
It can be used on the container side by making it a privileged container and setting device passthrough.

dev0: /dev/bus/usb/006/002
dev1: /dev/px4video0,mode=0664
dev2: /dev/px4video1,mode=0664
dev3: /dev/px4video2,mode=0664
dev4: /dev/px4video3,mode=0664
dev5: /dev/px4video4,mode=0664
dev6: /dev/px4video5,mode=0664
dev7: /dev/px4video6,mode=0664
dev8: /dev/px4video7,mode=0664
features: nesting=1

**Comment by aftertommy** [comment]
Yes! Thank you and I’m sorry — I should have updated this with that information.
