### ISSUE TITLE
[WinUSB] catファイルのハッシュが古いため、INFファイルがインストールできない。

### ISSUE THREAD

**Issue by knight-ryu12** [tsukumijima/px4_drv#7]
px4_drvの配布パッケージ(DTV-Buildのwinusb-240421とこのリポジトリ)のcatファイルがINFのSHA-1ハッシュに追従してないため、
```
[Window Title]
インストール エラー

[Main Instruction]
指定されたカタログ ファイルにファイルのハッシュがありません。ファイルが壊れているか、改ざんされた可能性があります。
```
と出て、インストールできません。

**Comment by tsukumijima** [comment]
この件どうもインストールできないらしいことはブログのコメント欄などでも情報頂いているのですが、個人的に余裕がなく対処までできていない状態です。
申し訳ありませんが、修正できる時間が取れるまでは当面は古い版のドライバーをお使いいただければと思います。基本的には旧版とさほど変わりはありませんので。

**Comment by tsukumijima** [comment]
@knight-ryu12 対応が遅くなり申し訳ありません！
https://github.com/tsukumijima/px4_drv/commit/f96562f267ed996a45150181b260759e9be96b17 にて修正しました。DTV-Builds リポジトリ内の [px4_drv_winusb-240421.zip](https://github.com/tsukumijima/DTV-Builds/raw/master/px4_drv_winusb-240421.zip) も上書き更新してあります。
一度お試しください。

**Comment by knight-ryu12** [comment]
インストールが正常に完了することが確認できました。
ありがとうございます！
